### ISSUE TITLE
dominate.util.text not escaping new lines with <br />

### ISSUE THREAD

**Issue by evandrocoan** [Knio/dominate#107]
If I add a text with `dominate.util.text()`, other characters as `<` and `>` are escaped correctly, except new lines which are not converted to `<br />`:
```python
        matched_text = "Escape-me\n<please>"
        doc = dominate.tags.font( color=color )
        with doc:
            dominate.util.text( matched_text )
```
Results in:
```html
<font color="#DDB700">Escape-me\n&lt;please&gt;</font>
```

Then, I am not sure how to put new lines inside it without manually escaping the input text and putting it inside the document using `dominate.util.raw()`.

**Comment by evandrocoan** [comment]
I just managed to do it with: 
```python
        matched_text = "Escape-me\n<please>"
        doc = dominate.tags.font( color=color )
        with doc:
            dominate.util.raw( dominate.util.escape( matched_text ).replace("\n", "<br />" ) )
```
-->
```html
<font color="#FF0000">Escape-me<br />&lt;please&gt;</font>
```

I am not sure I should close this, or may it is an enhancement to escape new lines with ``<br />``?

**Comment by Knio** [comment]
Escaping text is to _prevent_ conversion to HTML, (i.e. particularly in XSS attacks). Automatically adding tags would not be escaping, and is not a feature of dominate. Dominate is for providing direct Python classes for HTML constructs, and has the `br()` tag.

If you just want your page to render with line breaks, you could just leave the HTML as-is and use CSS to set the rendering mode (`white-space: pre;`, etc)

Or if you really want `<br>` tags, you could do something like this: (quick hack; has an extra `br` at the end)
```python
text = "Hello\nworld"
d = div((i, br()) for i in text.splitlines())
print(d)
```
Results:
```html
<div>Hello<br>world<br></div>
```

Or if you want more advanced text processing, use Markdown (or any other text processor) and put it in a `raw()` element.
