### ISSUE TITLE
lang tag in html ?

### ISSUE THREAD

**Issue by MaksymPylypenko** [Knio/dominate#109]
I just started using your library and it is awesome. I think an ability to add `lang` tag inside an `<html>` would be really helpful for rendering a multi-languge html.

> According to the W3C recommendation you should declare the primary language for each Web page with the lang attribute inside the <html> tag, like this:
```
<html lang="en">
...
</html>
```

**Comment by Knio** [comment]
Hi, you are able to do this:

```python
h = html(lang='en')
print(h)
```

Output:
```html
<html lang="en"></html>
```

Or:
```python
d = dominate.document()
d['lang'] = 'en'
print(d)
```

Output:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Dominate</title>
  </head>
  <body></body>
</html>
```
