### ISSUE TITLE
boolean attributes

### ISSUE THREAD

**Issue by jmcaine** [Knio/dominate#110]
It is not clear how one sets boolean (valueless) attributes, such as 'required' or 'autofocus'.  Neither the documentation nor the code seems to lend this information readily...?

**Comment by jmcaine** [comment]
W3C section 3.2.2 ("Boolean attributes") *does* say that you can use an empty-string value.  So apparently required="" would work.  I realize that you could not simply make boolean attributes positional args, as that's where the children go, not attributes.  I guess another option would be a designated kwarg named something like boolean_attributes that takes a list with those argument strings (names).

**Comment by Knio** [comment]
Hi,

Boolean arguments are supported by just passing boolean values. The implementation currently uses the string value of the attribute itself as the "true" value (which is supported by the html standard for these attributes)

Example:
```python
print(div(foo=True, bar=False))
```

```html
<div bar="false" foo="foo"></div>
```

**Comment by jmcaine** [comment]
Excellent, thank you.  Perhaps a little snippet in the documentation is in order.  It seems otherwise complete enough for major use cases,  I guess I could've found this if I'd dug deeper in the code.  Thank you for your quick response.
