### ISSUE TITLE
meta tag issues

### ISSUE THREAD

**Issue by Aladio** [Knio/dominate#116]
meta tag issues
-------------------------------------------------------------------------------------------
_input_
with doc.head:
meta('content="text/html;charset=utf-8", http-equiv="Content-Type"')
meta('content="utf-8", http-equiv="encoding"')
_output_
&lt;meta&gt;
&lt;meta&gt;
---------------------------------------------------------------------------------------------
_input_
with doc.head:
meta(raw('content="text/html;charset=utf-8" http-equiv="Content-Type"'))
meta(raw('content="utf-8" http-equiv="encoding"'))
_output_ 
&lt;meta&gt;
&lt;meta&gt;
--------------------------------------------------------------------------------------------------

**Comment by lachlankidson** [comment]
Try using [dictionary unpacking](https://docs.python.org/3.7/tutorial/controlflow.html#unpacking-argument-lists) to get around having a hyphen in the keyword:
```
with doc.head:
    meta(**{'content': 'text/html;charset=utf-8', 'http-equiv': 'Content-Type'})
    meta(**{'content': 'utf-8', 'http-equiv': 'encoding'})

print(doc)
```
**Output**
```
<!DOCTYPE html>
<html>
  <head>
    <title>Dominate your HTML</title>
    <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
    <meta content="utf-8" http-equiv="encoding">
  </head>
  <body></body>
</html>
```

**Comment by lachlankidson** [comment]
`meta(content='utf-8', **{'http-equiv': 'encoding'})` is also valid.

**Comment by Aladio** [comment]
Thank you!!

------ Original Message ------

**Comment by golightlyb** [comment]
This is special-cased so you can use an underscore: `http_equiv`:

`
    from dominate.tags import meta
    expected = '<meta content="text/html;charset=utf-8" http-equiv="Content-Type">'
    assert meta(content="text/html;charset=utf-8", http_equiv="Content-Type").render() == expected
`
