### ISSUE TITLE
<main> semantic element missing

### ISSUE THREAD

**Issue by StefanBrand** [Knio/dominate#117]
Hey, the [`<main>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main) element cannot be used. When I run the following:

```python
doc.add(main())
```

I get: `NameError: name 'main' is not defined`

**Comment by pyxdroid** [comment]
You can easily overload html_tag with missing tags before using it, like: 

class main(html_tag):pass

doc.add(main())
