### ISSUE TITLE
Underscores and aria-* tags

### ISSUE THREAD

**Issue by chesspac** [Knio/dominate#118]
Hello, 
All aria-* tags (used for bootstrap, for example) aren't converted when I write through named parameters where '-' are replaced by underscores. The only way I found is to use a dict and call it with **mydict
More generally, I have the problem with tags with dashes like 'data-page-size', the second dash wasn't converted.

Isn't there a bug?

Thanks

**Comment by golightlyb** [comment]
I've made a pull request to the maintainer to fix the problem with aria attributes.

I couldn't reproduce the same problem with "data-page-size". I included a test for this, which passes. 

What's your version of dominate? Do you have a code example that demonstrates the problem?

**Comment by chesspac** [comment]
Sorry for the mistake, a bad reading for my html generated code.
