### ISSUE TITLE
script with attribue 'async', 'defer'

### ISSUE THREAD

**Issue by accelsao** [Knio/dominate#122]
```
<script async defer 
          src="url"> </script>
```
I would like to render this code, but fail.

**Comment by Knio** [comment]
```python
s = script(defer=True, _async=True, src='url')
print(s.render())
```
Yields:
```html
<script async="async" defer="defer" src="url"></script>
```

1) `async` is a python keyword, so you must add an underscore to pass it as an attribute 
2) `async="async"` is the full way to specify boolean attributes in html (and is more compatable with xhtml)
