### ISSUE TITLE
Get current context element?

### ISSUE THREAD

**Issue by Cobertos** [Knio/dominate#123]
Is there a way to get the current element of the current context? It doesn't look like it's possible and is [only used internally](https://github.com/Knio/dominate/blob/master/dominate/dom_tag.py#L118).

It'd be nice to have an official function for this. Use case is for a file parsing problem where I want to add an `li` at a certain time and if the current parent is not a `ul`, I could create one on the fly and fill that `ul`.

**Comment by Cobertos** [comment]
Hacky, but you can take [this snippet](https://github.com/Knio/dominate/blob/master/dominate/dom_tag.py#L118) if you're working with a single thread...

```python
next(dom_tag._with_contexts.values())
```

**Comment by Knio** [comment]
This will be in 2.6.0
