### ISSUE TITLE
Examples in Manual reassigns Python keyword "input"

### ISSUE THREAD

**Issue by RoshVosh** [Knio/dominate#128]
Hi!
Love the pip package. I am finding it useful as a beginner in generating dynamic html with python. I just wanted to mention that in your example in the documentation you import as the following:

import dominate
**from dominate.tags import** *

However doing this reassigns the "input" python keyword. In other words after importing all (*) from dominate.tags globally in that module you can't use the input keyword. 

```
import dominate
from dominate.tags import *

var = input("Insert value: ")
print(var)
```

Example, the above code produces nothing.

I don't know if this was intentional but I don't believe it is the best way to showcase the features. 

Something like the following this might be better in the docs as an import block:

```
import dominate
import dominate.tags as dtags

dtags.a(href="somepage.html", etc)
```

**Comment by benjaminhonorio** [comment]
Same issue I found today. Thank you for your suggestion while importing, didn't think about that.

**Comment by Mrocza** [comment]
It's a bug in tags.py line 951:
`input = _input = input_`
While it should be:
`_input = input_`
Classes `del` and `map` don't have that assignment and work only with tailing underscore.

**Comment by benjaminhonorio** [comment]
You're rigth I modify it and it works fine now with the trailing underscore. Thanks
