### ISSUE TITLE
Rendered HTML is full of '=' and '3D' that we didn't code in

### ISSUE THREAD

**Issue by PropeReferio** [Knio/dominate#137]
I'm running Python 3.8.6 with Dominate 2.6.0.

I thought it was an issue with `raw()`, maybe, but when I rewrote the code, I still got all these `=` signs and `3D` in the HTML.

```
 with p():
        a(name="Why am I receiving this email notification?",
          href="https://anyurl.org/",
          style="text-decoration: none;")
    p(raw(
        """<a href="https://anyurl.org/", 
        style="text-decoration: none;">Why am I receiving this email notification?</a>
        """))
```

Below is the general structure of the code, the above `p` tags are nested in the same way as the last one in the below example:

```
  with self.doc:
      with table():
          with tr():
              with td(style=VERTICAL_ALIGN_TOP):
                  img(src=SOME_URL)
              with td():
                  with div(cls='header'):
                      p(raw("""<b>Do you see an issue with the Mapping?</b>"""))
```

When I look at the html file produced, it has `=` at the end of every line, at exactly 79 characters.

**Comment by PropeReferio** [comment]
Downgraded to Python 3.6.8, and this issue is fixed.

**Comment by Knio** [comment]
Can you provide a runnable example? CI shows no issues in Python 3.8

**Comment by PropeReferio** [comment]
I'm not sure how to provide such an example. Do you want me to paste some code?

**Comment by Knio** [comment]
Yes, some code that is executable by itself in a shell, like: https://repl.it/@Knio2/CalculatingVirtualCodeview
