### ISSUE TITLE
inline elements rendered with linebreak?

### ISSUE THREAD

**Issue by allefeld** [Knio/dominate#139]
Example: I'm trying to create a `p` element that contains the text "goodbye *cruel* world", i.e. with an inline `i` element:

````python
par = dominate.tags.p('goodbye ', dominate.tags.i('cruel'), ' world')
print(par.render())
````

Result:
````
<p>goodbye 
  <i>cruel</i> world
</p>
````

Why is there a linebreak `'\n'` inserted before (but not after) the `i` element? (Which can amount to the addition of whitespace.)

Alternatively, is there a way to directly specify the `innerHTML` of the `p` element? Something like

````python
dominate.tags.p(inner_html='goodbye <i>cruel</i> world')
````

**Comment by Knio** [comment]
This seems to be a bug in the `i` element not specifying inline (see: https://github.com/Knio/dominate/blob/master/dominate/tags.py#L703-L704)

As a workaround, you can pass `.render(pretty=False)` , or set the `is_pretty` property to False on `par` (ie if you want to maintain the pretty formatting for the rest of the document):

```python
>>> par.render(pretty=False)
'<p>goodbye <i>cruel</i> world</p>'

>>> par.is_pretty = False
>>> par.render()
'<p>goodbye <i>cruel</i> world</p>'
```
