### ISSUE TITLE
maximum recursion depth exceeded in comparison

### ISSUE THREAD

**Issue by coreybrett** [Knio/dominate#143]
The following code...
```
def hr():
    content = div(_class="row")
    with content.add(div(_class="col")):
        h3("HR Resources")
        hr()
        p("test")

    return content.render(pretty=current_app.debug)
```

Causes a `RecursionError: maximum recursion depth exceeded in comparison` exception.

I remove the call to `hr()`, the exception is no longer an issue, and the function works fine.

**Comment by Knio** [comment]
You redefined `hr()` and called it recursively.

**Comment by coreybrett** [comment]
facepalm
