### ISSUE TITLE
Allow to specify document language

### ISSUE THREAD

**Issue by roskakori** [Knio/dominate#144]
According to "[Declaring language in HTML](https://www.w3.org/International/questions/qa-html-language-declarations)" the recommended way to specify the language of an HTML document is:
```html
<html lang="en">...</html>
```
However, the document tag does not provide any means to set it:
```python
class document(tags.html):
  tagname = 'html'
  def __init__(self, title='Dominate', doctype='<!DOCTYPE html>', request=None):
```
It would be nice to have an optional parameter `lang=None` that if set to e.g. `lang='en'` would set the respective attribute for `<html>`.

AFAICT this would be a rather simple change in `document.render()`, so if you want I can look into it and submit a pull request.

**Comment by Knio** [comment]
`document` inherits from the tag class, so all the regular attribute setting methods work:
```python
d = dominate.document()
...
d['lang'] = 'en'
...
with d:
     dominate.tags.attr(lang='en')
...
d.set_attribute('lang','en')
...
print(d.render())
```
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Dominate</title>
  </head>
  <body></body>
</html>
````

Perhaps a fix to make it more convenient would be to just pass `**kwargs` to the super in the `document` constructor (and maybe `*args` into the body tag)

**Comment by roskakori** [comment]
Thanks!
