### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by mhillebrand** [Knio/dominate#161]
Are there any release notes that are a bit more informative? Maybe the issue numbers could be hyperlinks in the future?

<img width="546" alt="image" src="https://user-images.githubusercontent.com/286198/180828123-05ab7cc2-14b4-493b-9b84-708b62299ed8.png">

**Comment by Knio** [comment]
This is a hobby project, and I'm not interested nor have the time to be a package maintainer. I rarely even have time to review PRs.

Not being links seems like a GitHub bug. The release page has a compare button, I would suggest using this and looking at the `tests/` folder to see examples of all the new features.

![image](https://user-images.githubusercontent.com/83974/181172345-9158c1ec-189d-4ba3-a2b1-b9326b840f59.png)
