### ISSUE TITLE
Missing contextvars dependency

### ISSUE THREAD

**Issue by fpokryvk** [Knio/dominate#189]
This change https://github.com/Knio/dominate/commit/d72dca859ee4ed9113ce133fcd7d3c28cc54f54e introduced dependency on contextvars package, that is not installed by `pip3 install dominate`.

**Comment by modehnal** [comment]
We solved our current problem by fixing 2.9.0 version I imagine many will encounter the same issue.

**Comment by Knio** [comment]
what version of python are you on? I thought contextvars was stdlib.. :(

**Comment by modehnal** [comment]
It was failing on machines with python 3.6

**Comment by Knio** [comment]
3.6 is EOL - closing
