### ISSUE TITLE
Br tag is added as a new line instead of adding at the end of a line of text

### ISSUE THREAD

**Issue by Vittaly** [Knio/dominate#57]
Hi! my problem in subject

**Comment by vancheese** [comment]
Is there a workround?

**Comment by vancheese** [comment]
I've found a work around - If you enclose a bold tag in another tag and then ensure that do_inline is True
```
SB = b("Something Bold))
paragraph_thing = p()
paragraph_thing.do_inline = True
paragraph_thingy.add(SB)

**Comment by Knio** [comment]
Is there a standard way br tags should be written? (and should it be different than other tags?) I'd like to avoid making a special case for them unless dominate is doing something wrong according to the spec.

I am interested in making a more flexible api for being able to control whitespace/indentation however (#55)
