### ISSUE TITLE
Add a way to turn off character escaping

### ISSUE THREAD

**Issue by Kaljurand** [Knio/dominate#63]
Is there a way to preserve the quotation marks in the generated output? Current behavior escapes them to `&quot;`:

```
>>> print(script('alert("hello")', type='text/javascript'))
<script type="text/javascript">alert(&quot;hello&quot;)</script>

>>> print(comment('"'))
<!--&quot;-->
```

**Comment by Knio** [comment]
The same `raw` method from #64 will do this (and also not escape anything else)

If you only want to preserve `"` while still escaping everything else, try this:

```
>>> from dominate.tags import *
>>> from dominate.util import *
>>> print(div(raw(escape('alert("hello"); <>', quote=False))))
<div>alert("hello"); &lt;&gt;</div>
```
