### ISSUE TITLE
Allow nested tag functions that use a decorator with arguments

### ISSUE THREAD

**Issue by mnieber** [Knio/dominate#65]
The following code yields an assertion (if you try to execute `foo`), but it would be nice if it worked

    @span
    def foo():
        @div(_class="foobar")
        def bar():
            pass

        bar()

The code does work if you remove the arguments (`_class="foobar"`) from the decorator.

**Comment by Knio** [comment]
Closed in 9fdcafb

Not sure why the assert was there, but I added a test and it seems to work now. Let me know if there's any other weird behavior.
