### ISSUE TITLE
GPL3 License

### ISSUE THREAD

**Issue by brianbruggeman** [Knio/dominate#66]
Dominate is gpl3 - that means I'm going to avoid anything that uses it if I write commercial software.  Wish it was something more permissive.

Thanks.

**Comment by Knio** [comment]
Dominate is LGPL3, not GPL3, and is permitted to use the unmodified library in commercial software.

**Comment by brianbruggeman** [comment]
I disagree as Python obfuscates the "L" since it is not a binary and my lawyers would disagree too.  But thank you for clarifying.
