### ISSUE TITLE
Wrong html_tag for link

### ISSUE THREAD

**Issue by FZetting** [Knio/dominate#70]
When adding a link as child to a header as seen in the example, the resulting tag will look like
 <link href="style.css" rel="stylesheet">
As you see there is the closing '/' missied.

The bug is in dom_tag.py where you add the closing '>' without checking if the element is single and needs a '/>'.
possible solution:

add to the if not self.is_single:
    elif self.is_single:
      sb.append('/>')
    else:
      sb.append('>')

**Comment by DylanJ** [comment]
The `link` tag is what's known as a VOID element. In HTML5 the "/" character is optional.

See here : http://w3c.github.io/html-reference/syntax.html#void-element

**Comment by FZetting** [comment]
Sorry.

You are right. It was the editor who didn't know that and showed me an
error.

----- Ursprüngliche Nachricht -----
Von: "Knio/dominate" 
An:"Knio/dominate" 
Cc:"FZetting" , "Author" 
Gesendet:Mon, 25 Apr 2016 12:59:11 -0700
Betreff:Re: [Knio/dominate] Wrong html_tag for link (#70)

	The link tag is what's known as a VOID element. In HTML5 the "/"
character is optional. 

	See here :
http://w3c.github.io/html-reference/syntax.html#void-element [1] 

	—
You are receiving this because you authored the thread
Reply to this email directly or view it on GitHub [2]     

Links:
------
[1] http://w3c.github.io/html-reference/syntax.html#void-element
[2] https://github.com/Knio/dominate/issues/70#issuecomment-214501349
