### ISSUE TITLE
style tag is escaped

### ISSUE THREAD

**Issue by FZetting** [Knio/dominate#71]
The style tag is escaped.

In the style tag contains usually js code and this code should not be escaped.

**Comment by DylanJ** [comment]
Are you certain style tags usually contain JS?

**Comment by FZetting** [comment]
No, but if, they should not escaped. Espcially the double quotes. The
browser struggles when there is in the sources.

----- Ursprüngliche Nachricht -----
Von: "Knio/dominate" 
An:"Knio/dominate" 
Cc:"FZetting" , "Author" 
Gesendet:Mon, 25 Apr 2016 12:55:19 -0700
Betreff:Re: [Knio/dominate] style tag is escaped (#71)

	Are you certain style tags usually contain JS? 

	—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub [1]     

Links:
------
[1] https://github.com/Knio/dominate/issues/71#issuecomment-214499884

**Comment by DPDmancul** [comment]
Obviously the style tag doesn't contain js but css, and for this purpose shouldn't be escaped: for example `div > p` is a valid css selector, but writing in this way you got `div &gt; p` which is not valid css.
