### ISSUE TITLE
Adding a string to a tag's body while in tag context

### ISSUE THREAD

**Issue by cpitclaudel** [Knio/dominate#72]
Assume the following code:

```python
d = div()
with d:
    attr(id='header')
```

Which code can I use to add a string to `d`, while in the `with` block? Ideally, I was hopping for something like the following:

```python
d = div()
with d:
    attr(id='header')
    escaped("some text")
```

This would be equivalent to `d.add("some text")`, with the benefit of not needing a handle to `d`. I need this in the context of writing a visitor for an ANTLR parser: some notes, when visited, output a plain string, not an HTML tag. At a high level, the code looks like:

```python
d = div()
    visitor = Visitor()
    with p():
        visitor.visit(tree)
return d
```

And a visitor method might look like this:

```python
def visitA(self, ctx):
    with span("a"):
          attrs(name=ctx.label)
          self.visitChildren()
```

Thus the `visit*()` methods don't have a direct access to the context that they are in.

Let me know if I can make this clearer!

**Comment by Knio** [comment]
Hi,

You can use `text()` (or `raw()`) from the the `dominate.util` package within a context manager. 

The context manages also work across function calls so the visitor pattern should work as expected.

Sorry for the lack of documentation for these features!

**Comment by cpitclaudel** [comment]
Thanks!
