### ISSUE TITLE
dominate PyPi packaging issues

### ISSUE THREAD

**Issue by yegorich** [Knio/dominate#74]
I'm integrating dominate into embedded Linux distribution Buildroot and have run into some issues:

1.LICENSE.txt is missing in the ZIP file on PyPI. Could you add it?
2. it is much easier to integrate Python modules from PyPi when they are packages as *.tar.gz, that seems apply to the wast majority of packages there. Could you add dominate.tar.gz to PyPi

Thanks

**Comment by Knio** [comment]
What problems are you having with .zip vs .tar.gz? I mostly develop on windows and it defaults to creating zip but have no problems using the pypi package

**Comment by yegorich** [comment]
As long as you use PyPI directly it is not a problem, but in Buildroot all Python modules will be processed "manually". Archives will be downloaded and extracted into folder named python-pkgname. Tar based archives can be extracted to such a folder via tar's command line parameter. AFAIK unzip is not capable to do so. Hence  one has to perform intermediate steps to achieve the correct folder name. That's why it is preferable to also have dominate packaged as tar.gz archive.
