### ISSUE TITLE
add font class in tags python module

### ISSUE THREAD

**Issue by siva2503** [Knio/dominate#77]
I could not implement the font html tag with dominate, and i figured out  the tags.py module doesn't have a "font" class in it.

can you please add font html tag in the tags module to use with dominate.

**Comment by Knio** [comment]
Hi,

Thanks for the pull request! However, `<font>` is deprecated in HTML5: https://www.w3.org/TR/html5/obsolete.html

If you can, use a `<span style="font: ...">` instead. If you really need a `<font>` tag for compatibility, you can just add:

```python
class font(html_tag): pass
```

where you need it, similar to your PR.
