### ISSUE TITLE
free-format html?

### ISSUE THREAD

**Issue by jorythompson** [Knio/dominate#79]
I too am trying to set the different colors of different texts within a single heading.  Is there no way to just write your own html with this package?

**Comment by Knio** [comment]
I'm not sure what you mean by set colors, can you expand upon that?

However, you can always insert a raw html node like so:

```python
from dominate.tags import *
from dominate.util import raw

d = div(raw('''<span>raw html</span>'''))
print(d)
```

Ouput:
```html
<div><span>raw html</span></div>
```

https://repl.it/EQVt/0

**Comment by jorythompson** [comment]
That will work!  Thanks for your help

**Comment by haferburg** [comment]
That's very useful! Would be nice if this information could be found in the main README.md. Thank you for this nice library.
