### ISSUE TITLE
Release 2.3.0 is not tagged in git

### ISSUE THREAD

**Issue by sbraz** [Knio/dominate#81]
Hi, could you please tag 2.3.0 in git? At the moment, tags only exist for older versions.

**Comment by Knio** [comment]
Tagged 2.3.0 and 2.3.1

So I'm not usually in the habit of doing this when I make a new release, I'm curious what your use case is?

**Comment by sbraz** [comment]
Well I sometimes look at GH to see what the last version is (although PyPI is my reference when in doubt).
But it's mostly because I can easily see what a new version adds using git or GH's comparison feature: https://github.com/Knio/dominate/compare/2.2.1...2.3.0
