### ISSUE TITLE
ENH: LinkedData

### ISSUE THREAD

**Issue by westurner** [Knio/dominate#83]
Some of examples of building html containing linked data with dominate could be useful:
- [x] html5 data-key="value"
- [ ] HTML5  ( text/html; charset=utf-8 )
- [ ] XHTML + RDFa ( application/xhtml+xml )
- [ ] HTML5 + RDFa ( text/html; charset=utf-8 )
- [ ] HTML + JSONLD ( application/ld+json; charset=utf-8 )

References:
- https://wrdrd.com/docs/consulting/knowledge-engineering#rdfa #rdf #rdfs #schemaorg
- https://wrdrd.com/docs/consulting/knowledge-engineering#semantic-web-standards
- https://wrdrd.com/docs/consulting/knowledge-engineering#schemaorg
  - https://schema.org/
    - Wikipedia: https://en.wikipedia.org/wiki/Schema.org
    - Homepage: https://schema.org
    - Download: https://schema.org/version/latest/
    - Source: https://github.com/schemaorg/schemaorg
    - Source: https://github.com/schemaorg/schemaorg/tree/sdo-phobos/data/releases/2.2
    - Docs: http://dataliberate.com/2016/02/evolving-schema-org-in-practice-pt1-the-bits-and-pieces/
    - Issues: https://github.com/schemaorg/schemaorg/issues
    - IssueLabels: https://github.com/schemaorg/schemaorg/labels

**Comment by westurner** [comment]
Here's a PR with examples of adding OpenGraph RDFa, Twitter Cards metadata, and schema.org RDFa to an HTML page: https://github.com/CodeForAntarctica/codeforantarctica.github.io/pull/3

**Comment by Knio** [comment]
Hi,

I'm not sure exactly what you're asking for here.

dominate makes no semantic judgments on the values you give it - it does not try to validate html5 or any other standard, and is only concerned about syntax. You can pass any attributes into dominate and it will render it with minimal changes (underscores are mapped to dashes, see `data_key` below). Here is an example from your referenced document:

Code: https://repl.it/F10F
```python3
from dominate.tags import *

@html(prefix="og: http://ogp.me/ns#", lang="en", data_key="value")
def make_page():
  with head():
    meta(property="og:title", content="Code for Antarctica 🐧")
    meta(name="twitter:site", content="@CodeForAmerica")
    
  with body(vocab="http://schema.org/", typeof="WebPage"):
    h1("Code for Antarctica 🐧", property="name")
    img(property="image", src="img/adopta.jpg")
    
    
print(make_page())
```

Output:
```html
<html data-key="value" lang="en" prefix="og: http://ogp.me/ns#">
  <head>
    <meta content="Code for Antarctica 🐧" property="og:title">
    <meta content="@CodeForAmerica" name="twitter:site">
  </head>
  <body typeof="WebPage" vocab="http://schema.org/">
    <h1 property="name">Code for Antarctica 🐧</h1>
    <img property="image" src="img/adopta.jpg">
  </body>
</html>
```

Does this answer your question, or are you asking about automatically setting these attributes based on higher-level knowledge of the document?

**Comment by westurner** [comment]
Thanks for the examples of how to add OpenGraph RDFa, Twitter Cards, and
Schema.org RDFa with dominate for building the DOM.

This may be useful for generating JSONLD and RDFa metadata about/from/of
Jupyter notebooks ( westurner/nbmeta: obj._repr_html_())

Schema.org has a :mainEntity property which is useful for e.g. :WebPage
:CreativeWork s with a :name and :url which are :about another :Thing with
a :url

- http://schema.org/mainEntity
- P: mainEntity d: CreativeWork r: Thing
- P: Thing > Property > mainEntity

- http://schema.org/WebPage
- C: Thing > CreativeWork  > WebPage

And then, I want to:

- [ ] TST: verify that some or all of the {JSONLD, rdflib.Graph} data is
isomorphic to the triples yielded from parsing (and validating) the RDFa.

- [ ] ENH: rdflib.namespace.Namespace, NamespaceManager to RDFa prefix= attr

- [ ] HTML5 / XHTML
  - TIL HTML5, xml:base, and localhost
  -
https://dev.w3.org/html5/spec-preview/global-attributes.html#the-xml:base-attribute-(xml-only)
  "The xml:base attribute may be used on elements of XML documents. Authors
must not use the xml:base attribute in HTML documents."

**Comment by westurner** [comment]
These context managers ( ``__enter__``, ``__exit__``) are such a useful
pattern:
https://github.com/Knio/dominate/blob/master/README.md#context-managers

Thanks again!
