### ISSUE TITLE
Could not embed youtube video. Please update with this in your tags file. 

### ISSUE THREAD

**Issue by shanesaravia** [Knio/dominate#84]
Youtube embedded videos require "<iframe width="560" frameborder="1" allowfullscreen></iframe>"

Since "frameborder" and "allowfullscreen" needed to be within the "<>", i had to add them to the global attributes as seen below. (This file can be found at Python\Lib\site-packages\dominate\tags.py)

_ATTR_GLOBAL = set([
  'accesskey', 'class', 'class', 'contenteditable', 'contextmenu', 'dir',
  'draggable', 'id', 'item', 'hidden', 'lang', 'itemprop', 'spellcheck',
  'style', 'subject', 'tabindex', 'title', **'frameborder', 'allowfullscreen'**

When you want to embed a youtube video you can now just use this format as an example:

iframe(width="560", height="315", src="https://www.youtube.com/embed/Iqjy9UqKKuo", frameborder="0", allowfullscreen=True)

**Comment by Knio** [comment]
I think you may be using an extremely out of date version of dominate. It no longer tries to validate attribute names.

This code works fine: https://repl.it/F5bj/0
```python
from dominate.tags import *
i = iframe(width="560", height="315", src="https://www.youtube.com/embed/Iqjy9UqKKuo", frameborder="0", allowfullscreen=True)
print(i.render())
```

Output:
```html
<iframe allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/Iqjy9UqKKuo" width="560"></iframe>
```
