### ISSUE TITLE
Provide a way of adding text nodes to the current context

### ISSUE THREAD

**Issue by vfaronov** [Knio/dominate#85]
Currently, I have code like this:

```
def foo():
    with dominate.tags.p(__pretty=False):
        bar()

def bar():
    if something:
        dominate.tags.a(u'this is a link', ...)
    else:
        dominate.tags.span(u'just some text')
```

This produces HTML like this:

```
<p><span>just some text</span></p>
```

Problem is, I don’t actually want that `span`, but I need it because there’s no other way to add a text node to the current context. I wish I had some equivalent `dominate.tags.text()`. I have enough of these placeholder spans that they make page rendering perceptibly slower.

**Comment by Knio** [comment]
Hi,

You can do this with the `domuinate.util.text` function:

https://repl.it/GQ0i
```python

def foo():
  with p():
    bar()
  
def bar():
  text('Just some text')

```
```html
<p>Just some text</p>
```

**Comment by vfaronov** [comment]
Oh nice, thank you.
