### ISSUE TITLE
No way to override the title of an existing document

### ISSUE THREAD

**Issue by vfaronov** [Knio/dominate#87]
The readme says:

> You should notice that here the `head` tag contains zero children. This is because the default `title` tag is only added when the document is rendered and the `head` element does not explicitly contain one.

That sounds like very useful behavior, but it doesn’t work — the default `title` is added eagerly. For example, this program:

```
import dominate, dominate.tags
doc = dominate.document()
print(repr(doc.head))
with doc.head:
    dominate.tags.title('Test')
print(doc.render())
```

prints:

```
<dominate.tags.head at 7f0ac5025ba8: 0 attributes, 1 child>
<!DOCTYPE html>
<html>
  <head>
    <title>Dominate</title>
    <title>Test</title>
  </head>
  <body></body>
</html>
```

**Comment by Knio** [comment]
Sorry for the bad docs. You can update the title directly with the 'title' attribute with either a string or a title node.

```python
>>> d
=> <dominate.document "Dominate">
>>> d.title = "Test"
>>> d
=> <dominate.document "Test">
>>> d.title = title("Test 2")
>>> d
=> <dominate.document "Test 2">
```

**Comment by vfaronov** [comment]
@Knio Thanks!
