### ISSUE TITLE
How to use onclick method?

### ISSUE THREAD

**Issue by bifeng** [Knio/dominate#90]
```
import dominate
from dominate.tags import *
from dominate.util import text
doc = dominate.document(title='Dominate your HTML')

with doc.head:
    link(rel='stylesheet', href='responsive.css')  
    script(type='text/javascript', src='rbox.js')  

with doc:
    with p('You need to insert the ...'):
        text('[')
        # span('Click to Expand and see my code to insert',
        # title="Click to expand this topic or to contract a topic which has already been expanded",
        # cls="expand", onclick="return ExpandToggle(\'topic1\')")
        with span('Click to Expand and see my code to insert'):
            attr(title="Click to expand this topic or to contract a topic which has already been expanded")
            attr(cls="expand")
            attr(onclick="return ExpandToggle(\'topic1\')")
        text(' ]')
    with div(id="topic1", cls="expandedblock", style="display:none;"):
        p('The following is the code ...')

print(doc)
Html_file = open("test2.html", "w")
Html_file.write(str(doc))
Html_file.close()

```

**Comment by bifeng** [comment]
`import dominate
from dominate.tags import *
from dominate.util import text

doc = dominate.document(title='Dominate your HTML')

with doc.head:
link(rel='stylesheet', href='responsive.css')
script(type='text/javascript', src='rbox.js')

with doc:
with p('You need to insert the ...'):
text('[')
# span('Click to Expand and see my code to insert',
# title="Click to expand this topic or to contract a topic which has already been expanded",
# cls="expand", onclick="return ExpandToggle('topic1')")
with span('Click to Expand and see my code to insert'):
attr(title="Click to expand this topic or to contract a topic which has already been expanded")
attr(cls="expand")
attr(onclick="return ExpandToggle('topic1')")
text(' ]')
with div(id="topic1", cls="expandedblock", style="display:none;"):
p('The following is the code ...')
print(doc)
Html_file = open("test2.html", "w")
Html_file.write(str(doc))
Html_file.close()`

**Comment by bifeng** [comment]
`import dominate
from dominate.tags import *
from dominate.util import text

doc = dominate.document(title='Dominate your HTML')

with doc.head:
    link(rel='stylesheet', href='responsive.css')
    script(type='text/javascript', src='rbox.js')`

**Comment by bifeng** [comment]
import dominate
from dominate.tags import *
from dominate.util import text

doc = dominate.document(title='Dominate your HTML')

with doc.head:
    link(rel='stylesheet', href='responsive.css')
    script(type='text/javascript', src='rbox.js')

**Comment by bifeng** [comment]
> import dominate
from dominate.tags import *
from dominate.util import text

doc = dominate.document(title='Dominate your HTML')

with doc.head:
link(rel='stylesheet', href='responsive.css')
script(type='text/javascript', src='rbox.js')

**Comment by bifeng** [comment]
Output: You need to insert the ...[ Click to Expand and see my code to insert ]  
But i can't click it, how can i do?

**Comment by Knio** [comment]
Hi, the dominate code is producing the correct HTML. The error seems to be in your JavaScript library.
