### ISSUE TITLE
Not really an issue. Unicode chars

### ISSUE THREAD

**Issue by securisec** [Knio/dominate#95]
Hey, this is not really an issue, but i was wondering if you have anything built in or a way to handle unicode chars like `Malmö`. 

Depending on my use case, i am either getting a SyntaxError or a UnicodeEncodeError. Most of my functions return `str(object)` because i concatenate things later

And if there isnt something available to handle unicode, what would you say is the best way of handling these unicode chars?

Thanks!

**Comment by Knio** [comment]
Hi, dominate handles unicode fine. Your issue is likely how you are dealing with unicode strings, how your IO is set up, or something else, but I cannot say without seeing a specific example including which version of Python. There are many tutorials on how to use unicode in Python.
