### ISSUE TITLE
Bug in a tag when using '&' char in the href url

### ISSUE THREAD

**Issue by pymaldebaran** [Knio/dominate#96]
When providing an url to the href attribute of an a node the '&' character is always escaped therefore modifying the url. As the '&' is commonly used to separate parameters in url this is quite problematic.

Very simple to reproduce:

```
>>> from dominate.tags import a
>>> test = a('toto', href='https://test.org/aaa?a=b&c=d')
>>> test.render()
'<a href="https://test.org/aaa?a=b&amp;c=d">toto</a>'
```
Here we have a '&amp;' instead of '&'. What would be expected is:

```
>>> from dominate.tags import a
>>> test = a('toto', href='https://test.org/aaa?a=b&c=d')
>>> test.render()
'<a href="https://test.org/aaa?a=b&c=d">toto</a>'
```
Or am I missing something?

BTW I tried to use `href=raw('https://test.org/aaa?a=b&c=d')` but with no luck (this was a desperate attempt).

**Comment by pymaldebaran** [comment]
I did some digging... it seem the same thing happens not only on href attributes but with all attributes. I think all attribute contents are escaped & --> &amp; 

I think it is a good idea for all the general purpose attributes (in order not to screw up the whole html) but if the attribute is href it needs to keep its precious & as-is.

I will loo, at the code and try to provide a PR asap.

**Comment by Knio** [comment]
Hi,
Thanks for the report. This is an interesting edge case, however, I think dominate is actually compliant with the HTML spec here. A browser should be decoding the `&amp;` in the attribute value source and creating the link with the correctly decoded href.

[1] https://html.spec.whatwg.org/multipage/syntax.html#syntax-attribute-value
> Attribute values are a mixture of text and character references, except with the additional restriction that the text cannot contain an ambiguous ampersand.

Try saving this to a file, and clicking on the link. The URL bar after clicking, and httpbin results should confirm that it's been decoded:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
  </head>
  <body>
    <a href="https://httpbin.org/get?foo=bar&amp;x=y">test</a>
  </body>
</html>
```

However, it does look odd to people reading the source code, and would also be legal to just render `&` as long as it is unambiguous [2]. The escape mechanism then would have to be smarter and ensure that it can't be interpreted as a character reference, so we can't just disable all escaping of `&` characters.

[2] https://html.spec.whatwg.org/multipage/syntax.html#syntax-ambiguous-ampersand

**Comment by pymaldebaran** [comment]
Oh this is right ! thanks for the link to the spec, this is very instructive.

I tested your mini page for test and, indeed, this works like a charm. 

> However, it does look odd to people reading the source code

In my case it's my unittest find this beheavior odd since it was searching for the exact original link in my generated page. So I will modify my test to be more HTML spec compatible.

It seems quite strange that the python std lib does not provide any way to encode/decode url using named characters... even urllib.parse only provides way to %encode urls... #sad I think I will have to mimic your "encode" function and provide an equivalent "decode" since this is quite trivial in our case.

I test everything and give you an update if everything works well.

**Comment by pymaldebaran** [comment]
Everything worked perfectly once I modified my unittest to conform to the HTML spec (and obviously I also tested the resulting page in a browser !).

(maybe I will investigate the python mailing lists to find why there is no named character decoder/encoder func provided in the std lib... who knows maybe this will lead to a PIP...)

Thanks a lot for your thorough answer !
