### ISSUE TITLE
Create attributes without quotation marks

### ISSUE THREAD

**Issue by skjerns** [Knio/dominate#98]
I want to create the following code:

```
<code style=display:block;white-space:pre-wrap>
import numpy
import sys
</code>
```
for this I"m using:
```
doc = document()
with doc:
    with tags.code('import numpy\nimport sys') as cc:
        cc['style']='display:block'
        cc['white_space']='pre_wrap'
```
it will create it as 
```
<code style=display:"block" white-space:"pre-wrap">
import numpy
import sys
</code>
```
And then the attributes are being ignored by my browser.

PS: I'm a HTML noob, so there is surely a better way to do that.

**Comment by Knio** [comment]
You are trying to set CSS parameters as if they are HTML attributes.

The correct way to do this would be:

`cc['style'] = 'display: block; white-space: pre-wrap'`
